### ISSUE TITLE
Misleading image for #facebook slide

### ISSUE THREAD

**Issue by damooo** [RubenVerborgh/Technology-Human-Rights-2022#1]
Hello @RubenVerborgh , The slide about facebook with image `zuckerberg.jpg`, and following slide about #freebasics campaign is misleading.

GOI representative share dias with many business group representatives. And that doesn't implies their support for dubious campaigns. Even after intense lobbying and blackmail from facebook, and aligned business, and ads in newspapers, televisions, Telecom Regulatory Authority of India slammed facebook in strongest words, and changed public narrative. And made sure word `Net nutrality` popular in public discource.

Narendra Modi has nothing in support of zuckerburg or freebasics campaign, even if he shared stage with them in a photo. Instead he is responsible for making undifferentiated internet connectivity reaching to remotest corners and villages of nation.

Comment is not in support of GOI.

**Comment by RubenVerborgh** [comment]
Hi @damooo,

Thanks for the feedback!

> Narendra Modi has nothing in support of zuckerburg or freebasics campaign, even if he shared stage with them in a photo. Instead he is responsible for making undifferentiated internet connectivity reaching to remotest corners and villages of nation.

Indeed; and the claim of the slide is that "Facebook _tries_ to replace the open Web that enabled it to exist."
Zuck indeed went around shaking hands, unsuccessfully.

I tell this to people when presenting these slides; note that the slide in question links to [this Guardian article](https://www.theguardian.com/technology/2016/may/12/facebook-free-basics-india-zuckerberg#img-5) which explains the context.
